port: 5000
OUTPUT_PATH: 'C:\Users\nicol\OneDrive\Escritorio\tg\DICOM-Processor\ms-dicom-slicer\OUTPUT'
S3_BUCKET_ARN: 'arn:aws:s3:::s3-dicom-processor'
S3_BUCKET_NAME: 's3-dicom-processor'
AWS_ACCESS_KEY_ID: 'AKIA53KZLOZJ4X3S5J3X'
AWS_SECRET_ACCESS_KEY: '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'
DATABASE_HOST: 'database-1.cbtbx79jvpr1.us-east-2.rds.amazonaws.com'
DATABASE_USERNAME: 'admin'
DATABASE_PASSWORD: 'trabajogrado'
DATABASE_SCHEMA: 'backend_gui_nodules'
#send_S3: True
#width: 32
#height: 32
#depth: 5
#debug: False
#circle_radius: 10
#circle_width: 2
#circle_color: 'red'
#compress_level: 5
#gz_compression: True