port: 4250
LIDC_path_prod: 'D:\JAVERIANA\TG\Modelo\LIDC-IDRI_images_npy_3d_HU_TEST'
weight_paths: 'D:\JAVERIANA\TG\Modelo\Multi-attention-nodule-classification\Journal_SPIE_binary_Ind_Inferences\Journal_SPIE_1S_2H_binary_kfold_fold_'
LIDC_path: 'D:\JAVERIANA\TG\Modelo\LIDC-IDRI_images_npy_3d_HU'