spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: route-ms-nodule-classifier
          uri: http://localhost:4250/
          predicates:
            - Path=/ms-nodule-classifier/**
          filters:
            - StripPrefix=1

        - id: route-ms-admon
          uri: http://localhost:8081/
          predicates:
            - Path=/ms-admon/**
          filters:
            - StripPrefix=1

        - id: route-ms-dicom-slicer
          uri: http://localhost:5000/
          predicates:
            - Path=/ms-dicom-slicer/**
          filters:
            - StripPrefix=1

        - id: route-sqs-queue
          uri: http://localhost:5000/
          predicates:
            - Path=/sqs-queue/**
          filters:
            - StripPrefix=1
server:
  port: 9000