spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://database-1.cbtbx79jvpr1.us-east-2.rds.amazonaws.com:3306/backend_gui_nodules?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

server:
  port: 8082